import Joi from 'joi'

export const articleValidator = {
  create: Joi.object({
    title: Joi.string().required(),
    slug: Joi.string().optional(),
    excerpt: Joi.string().allow('', null).optional(),
    content: Joi.alternatives().try(Joi.object(), Joi.string()).required(),
    featured_image_url: Joi.string().allow('', null).optional(),
    coverImage: Joi.string().allow('', null).optional(),
    cover_image: Joi.string().allow('', null).optional(),
    author_id: Joi.string().optional(),
    authorId: Joi.string().optional(),
    author: Joi.alternatives().try(Joi.object(), Joi.string()).optional(),
    authorName: Joi.string().allow('', null).optional(),
    author_name: Joi.string().allow('', null).optional(),
    authorAvatar: Joi.string().allow('', null).optional(),
    author_avatar: Joi.string().allow('', null).optional(),
    authorRole: Joi.string().allow('', null).optional(),
    author_role: Joi.string().allow('', null).optional(),
    category: Joi.string().allow('', null).optional(),
    tags: Joi.array().items(Joi.string()).optional(),
    readTimeMinutes: Joi.number().optional(),
    read_time_minutes: Joi.number().optional(),
    seo_title: Joi.string().allow('', null).optional(),
    seoTitle: Joi.string().allow('', null).optional(),
    seo_description: Joi.string().allow('', null).optional(),
    seoDescription: Joi.string().allow('', null).optional(),
    seo_keywords: Joi.string().allow('', null).optional(),
    seoKeywords: Joi.string().allow('', null).optional(),
    is_published: Joi.boolean().optional(),
    isPublished: Joi.boolean().optional(),
    isActive: Joi.boolean().optional(),
    is_active: Joi.boolean().optional(),
  }),
  update: Joi.object({
    title: Joi.string().optional(),
    slug: Joi.string().optional(),
    excerpt: Joi.string().allow('', null).optional(),
    content: Joi.alternatives().try(Joi.object(), Joi.string()).optional(),
    featured_image_url: Joi.string().allow('', null).optional(),
    coverImage: Joi.string().allow('', null).optional(),
    cover_image: Joi.string().allow('', null).optional(),
    author_id: Joi.string().optional(),
    authorId: Joi.string().optional(),
    author: Joi.alternatives().try(Joi.object(), Joi.string()).optional(),
    authorName: Joi.string().allow('', null).optional(),
    author_name: Joi.string().allow('', null).optional(),
    authorAvatar: Joi.string().allow('', null).optional(),
    author_avatar: Joi.string().allow('', null).optional(),
    authorRole: Joi.string().allow('', null).optional(),
    author_role: Joi.string().allow('', null).optional(),
    category: Joi.string().allow('', null).optional(),
    tags: Joi.array().items(Joi.string()).optional(),
    readTimeMinutes: Joi.number().optional(),
    read_time_minutes: Joi.number().optional(),
    seo_title: Joi.string().allow('', null).optional(),
    seoTitle: Joi.string().allow('', null).optional(),
    seo_description: Joi.string().allow('', null).optional(),
    seoDescription: Joi.string().allow('', null).optional(),
    seo_keywords: Joi.string().allow('', null).optional(),
    seoKeywords: Joi.string().allow('', null).optional(),
    is_published: Joi.boolean().optional(),
    isPublished: Joi.boolean().optional(),
    isActive: Joi.boolean().optional(),
    is_active: Joi.boolean().optional(),
  }).min(1),
}
