import Joi from 'joi'

export const bookingValidator = {
  create: Joi.object({
    tripId: Joi.string().optional(),
    trip_id: Joi.string().optional(),
    destinationId: Joi.string().optional(),
    destination_id: Joi.string().optional(),
    fullName: Joi.string().min(2).max(255).optional(),
    full_name: Joi.string().min(2).max(255).optional(),
    name: Joi.string().min(2).max(255).optional(),
    email: Joi.string().email().optional(),
    phoneNumber: Joi.string().optional(),
    phone_number: Joi.string().optional(),
    phone: Joi.string().optional(),
    country: Joi.string().optional(),
    nationality: Joi.string().optional(),
    gender: Joi.string().valid('male', 'female', 'other').allow('', null).optional(),
    date_of_birth: Joi.date().iso().optional(),
    dateOfBirth: Joi.date().iso().optional(),
    healthNotes: Joi.string().allow('', null).optional(),
    health_notes: Joi.string().allow('', null).optional(),
    preferred_language: Joi.string().allow('', null).optional(),
    preferredLanguage: Joi.string().allow('', null).optional(),
    pickupLocation: Joi.string().allow('', null).optional(),
    pickup_location: Joi.string().allow('', null).optional(),
    pickupLatitude: Joi.number().allow(null).optional(),
    pickup_latitude: Joi.number().allow(null).optional(),
    pickupLongitude: Joi.number().allow(null).optional(),
    pickup_longitude: Joi.number().allow(null).optional(),
    pickupNotes: Joi.string().allow('', null).optional(),
    pickup_notes: Joi.string().allow('', null).optional(),
    departure_date: Joi.date().iso().optional(),
    departureDate: Joi.date().iso().optional(),
    return_date: Joi.date().iso().optional(),
    returnDate: Joi.date().iso().optional(),
    price_per_pax: Joi.number().optional(),
    pricePerPax: Joi.number().optional(),
    duration_days: Joi.number().optional(),
    durationDays: Joi.number().optional(),
    captchaToken: Joi.string().optional(),
    captcha_token: Joi.string().optional(),
    'g-recaptcha-response': Joi.string().optional(),
    gRecaptchaResponse: Joi.string().optional(),
  })
    .or('tripId', 'trip_id', 'destinationId', 'destination_id')
    .or('fullName', 'full_name', 'name')
    .or('phoneNumber', 'phone_number', 'phone'),
}
