import Joi from 'joi'

export const destinationValidator = {
  create: Joi.object({
    name: Joi.string().min(2).max(255).optional(),
    title: Joi.string().min(2).max(255).optional(),
    slug: Joi.string().allow('', null).optional(),
    tagline: Joi.string().allow('', null).optional(),
    description: Joi.string().allow('', null).optional(),
    image_url: Joi.string().allow('', null).optional(),
    coverImage: Joi.string().allow('', null).optional(),
    cover_image: Joi.string().allow('', null).optional(),
    location: Joi.string().allow('', null).optional(),
    price_per_person: Joi.number().positive().optional(),
    pricePerPax: Joi.number().positive().optional(),
    duration_days: Joi.number().integer().positive().allow(null).optional(),
    durationDays: Joi.number().integer().positive().allow(null).optional(),
    duration_nights: Joi.number().integer().min(0).allow(null).optional(),
    durationNights: Joi.number().integer().min(0).allow(null).optional(),
    galleryImages: Joi.array().items(Joi.string()).optional(),
    gallery_images: Joi.array().items(Joi.string()).optional(),
    inclusions: Joi.array().items(Joi.string()).optional(),
    exclusions: Joi.array().items(Joi.string()).optional(),
    highlights: Joi.array().items(Joi.string()).optional(),
    rating: Joi.number().min(0).max(5).optional(),
    totalReviews: Joi.number().min(0).optional(),
    total_reviews: Joi.number().min(0).optional(),
    isPopular: Joi.boolean().optional(),
    is_popular: Joi.boolean().optional(),
    meetingPoint: Joi.string().allow('', null).optional(),
    meeting_point: Joi.string().allow('', null).optional(),
    maxGroupCapacity: Joi.number().integer().positive().optional(),
    max_group_capacity: Joi.number().integer().positive().optional(),
    itinerary: Joi.alternatives().try(Joi.object(), Joi.array()).optional(),
    is_active: Joi.boolean().optional(),
    isActive: Joi.boolean().optional(),
  }).or('name', 'title'),

  update: Joi.object({
    name: Joi.string().min(2).max(255).optional(),
    title: Joi.string().min(2).max(255).optional(),
    slug: Joi.string().allow('', null).optional(),
    tagline: Joi.string().allow('', null).optional(),
    description: Joi.string().allow('', null).optional(),
    image_url: Joi.string().allow('', null).optional(),
    coverImage: Joi.string().allow('', null).optional(),
    cover_image: Joi.string().allow('', null).optional(),
    location: Joi.string().allow('', null).optional(),
    price_per_person: Joi.number().positive().optional(),
    pricePerPax: Joi.number().positive().optional(),
    duration_days: Joi.number().integer().positive().allow(null).optional(),
    durationDays: Joi.number().integer().positive().allow(null).optional(),
    duration_nights: Joi.number().integer().min(0).allow(null).optional(),
    durationNights: Joi.number().integer().min(0).allow(null).optional(),
    galleryImages: Joi.array().items(Joi.string()).optional(),
    gallery_images: Joi.array().items(Joi.string()).optional(),
    inclusions: Joi.array().items(Joi.string()).optional(),
    exclusions: Joi.array().items(Joi.string()).optional(),
    highlights: Joi.array().items(Joi.string()).optional(),
    rating: Joi.number().min(0).max(5).optional(),
    totalReviews: Joi.number().min(0).optional(),
    total_reviews: Joi.number().min(0).optional(),
    isPopular: Joi.boolean().optional(),
    is_popular: Joi.boolean().optional(),
    meetingPoint: Joi.string().allow('', null).optional(),
    meeting_point: Joi.string().allow('', null).optional(),
    maxGroupCapacity: Joi.number().integer().positive().optional(),
    max_group_capacity: Joi.number().integer().positive().optional(),
    itinerary: Joi.alternatives().try(Joi.object(), Joi.array(), Joi.allow(null)).optional(),
    is_active: Joi.boolean().optional(),
    isActive: Joi.boolean().optional(),
  }).min(1),
}
