import Joi from 'joi'

export const driverValidator = {
  create: Joi.object({
    user_id: Joi.string().optional(),
    userId: Joi.string().optional(),
    fullName: Joi.string().optional(),
    name: Joi.string().optional(),
    phoneNumber: Joi.string().optional(),
    phone: Joi.string().optional(),
    email: Joi.string().email().optional(),
    license_number: Joi.string().min(3).max(100).optional(),
    licenseNumber: Joi.string().min(3).max(100).optional(),
    vehicle_type: Joi.string().min(2).max(100).optional(),
    vehicleType: Joi.string().min(2).max(100).optional(),
    vehicleModel: Joi.string().min(2).max(100).optional(),
    vehicle_plat: Joi.string().min(3).max(50).optional(),
    vehiclePlat: Joi.string().min(3).max(50).optional(),
    plateNumber: Joi.string().min(3).max(50).optional(),
    experience_years: Joi.number().integer().min(0).optional(),
    experienceYears: Joi.number().integer().min(0).optional(),
    passengerCapacity: Joi.number().optional(),
    status: Joi.string().optional(),
    photoUrl: Joi.string().allow('', null).optional(),
    rating: Joi.number().min(0).max(5).optional(),
    is_available: Joi.boolean().optional(),
    isAvailable: Joi.boolean().optional(),
  }),
  update: Joi.object({
    fullName: Joi.string().optional(),
    name: Joi.string().optional(),
    phoneNumber: Joi.string().optional(),
    phone: Joi.string().optional(),
    email: Joi.string().email().optional(),
    license_number: Joi.string().min(3).max(100).optional(),
    licenseNumber: Joi.string().min(3).max(100).optional(),
    vehicle_type: Joi.string().min(2).max(100).optional(),
    vehicleType: Joi.string().min(2).max(100).optional(),
    vehicleModel: Joi.string().min(2).max(100).optional(),
    vehicle_plat: Joi.string().min(3).max(50).optional(),
    vehiclePlat: Joi.string().min(3).max(50).optional(),
    plateNumber: Joi.string().min(3).max(50).optional(),
    experience_years: Joi.number().integer().min(0).optional(),
    experienceYears: Joi.number().integer().min(0).optional(),
    passengerCapacity: Joi.number().optional(),
    status: Joi.string().optional(),
    photoUrl: Joi.string().allow('', null).optional(),
    rating: Joi.number().min(0).max(5).optional(),
    is_available: Joi.boolean().optional(),
    isAvailable: Joi.boolean().optional(),
  }).min(1),
}
